banking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import include, path

from accounts.views import AccountLoginView, SignUpView
from core.views import HomeView


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("admin/", admin.site.urls),
    path("transactions/", include("transactions.urls", namespace="transactions")),
    path("credits/", include("credits.urls", namespace="credits")),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    # Change Password
    path(
        "change-password/",
        PasswordChangeView.as_view(
            template_name="commons/password_change.html", success_url="/"
        ),
        name="change_password",
    ),
    # Forget Password
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="commons/password-reset/password_reset.html",
            subject_template_name="commons/password-reset/password_reset_subject.txt",
            success_url="/login/",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="commons/password-reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="commons/password-reset/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="commons/password-reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

credits/urls.py
from django.urls import path

from accounts.views import AccountLoginView
from credits.views import credit_list, apply_credit, approve_credit, active_credits

app_name = "credits"
urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("list/", credit_list, name="credit_list"),
    path("apply", apply_credit, name="apply_credit"),
    path("approve/<int:credit_app_id>/", approve_credit, name="approve_credit"),
    path("active_credits/", active_credits, name="active_credits"),
]

credits/models.py
from django.db import models

from accounts.models import User
from credits.constants import CREDIT_STATUS, STATUS


class CreditApplication(models.Model):
    user = models.ForeignKey(
        User,
        related_name="user_credit_application",
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    purpose = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=CREDIT_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)


class Credit(models.Model):
    user = models.ForeignKey(
        User,
        related_name="user_credit",
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    term_months = models.PositiveIntegerField()
    monthly_payment = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

credits/forms.py
from django import forms

from credits.models import CreditApplication


class CreditApplicationForm(forms.ModelForm):
    class Meta:
        model = CreditApplication
        fields = ["amount", "purpose"]

    def clean_amount(self):
        amount = self.cleaned_data.get("amount")
        if amount is not None and amount <= 0:
            raise forms.ValidationError("Amount must be a positive number.")
        return amount


class CreditApprovalForm(forms.Form):
    approved = forms.BooleanField(label="Approve credits", required=False)

credits/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required

from accounts.models import Card
from credits.forms import CreditApprovalForm, CreditApplicationForm
from credits.models import CreditApplication, Credit


@staff_member_required
def credit_list(request):
    credit_applications = CreditApplication.objects.all()
    return render(
        request,
        "credits/credit_list.html",
        {"credit_applications": credit_applications},
    )


@login_required
def apply_credit(request):
    if request.method == "POST":
        form = CreditApplicationForm(request.POST)
        if form.is_valid():
            credit_application = form.save(commit=False)

            credit_application.user = (
                request.user._wrapped
                if hasattr(request.user, "_wrapped")
                else request.user
            )
            credit_application.status = "PENDING"
            credit_application.save()

            messages.success(
                request, "Credit application submitted. Awaiting approval."
            )
            return redirect("accounts:user_profile")
    else:
        form = CreditApplicationForm()

    return render(request, "credits/credit_application_form.html", {"form": form})


@staff_member_required
def approve_credit(request, credit_app_id):
    credit_application = get_object_or_404(CreditApplication, id=credit_app_id)

    if request.method == "POST":
        form = CreditApprovalForm(request.POST)
        if form.is_valid():
            approved = form.cleaned_data["approved"]

            if approved:
                # Process the approved credits application
                Credit.objects.create(
                    user=credit_application.user,
                    amount=credit_application.amount,
                    interest_rate=5.0,
                    term_months=12,
                    monthly_payment=calculate_monthly_payment(
                        credit_application.amount
                    ),
                    remaining_amount=credit_application.amount,
                    status="APPROVED",
                )
                if Card.objects.filter(
                    user=credit_application.user,
                    card_name=f"Credit: {credit_application.purpose}",
                ).exists():
                    raise ValidationError("Card already exists for this Credit")

                # Create associated card
                Card.objects.create(
                    card_name=f"{credit_application.purpose} Credit",
                    user=credit_application.user,
                    card_type="C",
                    balance=credit_application.amount,
                    currency="B",
                )

                messages.success(
                    request, "Credit and card created. Review and confirm to proceed."
                )

                credit_application.status = "APPROVED"
                credit_application.save()

                messages.success(request, f"Credit application approved.")
            else:
                # Reject the credits application
                credit_application.status = "REJECTED"
                credit_application.save()

                messages.warning(request, f"Credit application rejected.")

            return redirect("credits:credit_list")

    else:
        form = CreditApprovalForm()

    return render(
        request,
        "credits/credit_approval_form.html",
        {"form": form, "credit_application": credit_application},
    )


def calculate_monthly_payment(loan_amount):
    interest_rate = Decimal("0.05")
    term_months = Decimal("12")

    monthly_interest_rate = interest_rate / Decimal("12")
    monthly_payment = (loan_amount * monthly_interest_rate) / (
        Decimal("1") - (Decimal("1") + monthly_interest_rate) ** -term_months
    )

    return round(monthly_payment, 2)


@login_required
def active_credits(request):
    user_credits = Credit.objects.filter(user=request.user, status="APPROVED")
    return render(
        request, "credits/active_credits.html", {"user_credits": user_credits}
    )

templates/credits/active_credits.html
{% extends 'core/base.html' %}
{% block content %}
<div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
  <h2 class="text-2xl font-semibold mb-4">Active Credits</h2>

  <ul>
    {% for credit in user_credits %}
      <li class="border-b border-gray-300 py-4">
        <div>
          <span class="text-gray-700 font-bold">Amount:</span> {{ credit.amount }} BYN<br>
          <span class="text-gray-700 font-bold">Interest Rate:</span> {{ credit.interest_rate }} %<br>
          <span class="text-gray-700 font-bold">Term Months:</span> {{ credit.term_months }} <br>
          <span class="text-gray-700 font-bold">Monthly Payment:</span> {{ credit.monthly_payment }} BYN<br>
        </div>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/credits/credit_application_form.html
{% extends 'core/base.html' %}
{% block content %}
<div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
  <h2 class="text-2xl font-semibold mb-4">Credit Application</h2>

  <form method="post" class="space-y-4">
    {% csrf_token %}

    <div class="mb-4">
      <label for="{{ form.amount.id }}" class="block text-gray-700 text-sm font-bold mb-2">Amount:</label>
      <input type="number" name="{{ form.amount.name }}" id="{{ form.amount.id }}" class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="Enter the amount" >
      {% if form.amount.errors %}
        <p class="text-red-500 text-sm">{{ form.amount.errors.0 }}</p>
      {% endif %}
    </div>

    <div class="mb-4">
      <label for="{{ form.purpose.id }}" class="block text-gray-700 text-sm font-bold mb-2">Purpose:</label>
      <input type="text" name="{{ form.purpose.name }}" id="{{ form.purpose.id }}" class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="Enter the purpose">
      {% if form.purpose.errors %}
        <p class="text-red-500 text-sm">{{ form.purpose.errors.0 }}</p>
      {% endif %}
    </div>

    <button type="submit" class="flex text-center mx-auto justify-center bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
      Submit
    </button>

    {% if form.errors %}
      <p class="text-red-500 text-sm mt-4">{{ form.non_field_errors.0 }}</p>
    {% endif %}
  </form>
</div>
{% endblock %}

templates/credits/credit_approval_form.html
{% extends 'core/base.html' %}
{% block content %}
<div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
  <h2 class="text-2xl font-semibold mb-4">Credit Application Approval</h2>

  <p>Application Status: {{ credit_application.status }}</p>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
      Approve
    </button>
  </form>

  <a href="{% url 'credits:credit_list' %}" class="text-blue-500 hover:underline">Back to Credit List</a>
</div>
{% endblock %}

templates/credits/credit_list.html
{% extends 'core/base.html' %}
{% block content %}
<div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
  <h2 class="text-2xl font-semibold mb-4">Credit Applications</h2>

  <ul>
    {% for credit_application in credit_applications %}
      <li class="border-b border-gray-300 py-4">
        <div class="flex items-center justify-between">
          <div>
            <span class="text-gray-700 font-bold">Amount:</span> {{ credit_application.amount }} <br>
            <span class="text-gray-700 font-bold">Purpose:</span> {{ credit_application.purpose }} <br>
            <span class="text-gray-700 font-bold">Status:</span> {{ credit_application.status }} <br>
          </div>
          {% if credit_application.status == 'PENDING' %}
            <a href="{% url 'credits:approve_credit' credit_application.id %}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
              Approve
            </a>
          {% endif %}
        </div>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}