accounts/urls.py
from django.urls import path
from .views import (
    LogoutView,
    UserProfileView,
    CardCreateView,
    CardListView,
    deposit_card,
    StaffProfileView,
    make_payment,
    statement,
    deposit_approval,
    deposit_approval_list,
    create_budgeting_system,
    budgeting_systems_list,
    delete_budgeting_system,
    EditUserAddressView,
    AccountLoginView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("profile-edit/", EditUserAddressView.as_view(), name="edit_profile"),
    path("staff_profile/", StaffProfileView.as_view(), name="staff_profile"),
    path("make_payment/", make_payment, name="make_payment"),
    path("create_card/", CardCreateView.as_view(), name="create_card"),
    path("card_list/", CardListView.as_view(), name="card_list"),
    path("card_history/<int:card_id>", statement, name="card_history"),
    path("deposit_card/<int:card_id>", deposit_card, name="deposit_form"),
    path("deposit-approval/", deposit_approval_list, name="deposit_approval_list"),
    path("deposit-approval/<int:card_id>/", deposit_approval, name="deposit_approval"),
    path(
        "budgeting-system/create/",
        create_budgeting_system,
        name="create_budgeting_system",
    ),
    path(
        "budgeting-systems-list/", budgeting_systems_list, name="budgeting_systems_list"
    ),
    path(
        "delete-budgeting-system/<int:budgeting_system_id>/",
        delete_budgeting_system,
        name="delete_budgeting_system",
    ),
]

banking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import include, path

from accounts.views import AccountLoginView, SignUpView
from core.views import HomeView


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("admin/", admin.site.urls),
    path("transactions/", include("transactions.urls", namespace="transactions")),
    path("credits/", include("credits.urls", namespace="credits")),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    # Change Password
    path(
        "change-password/",
        PasswordChangeView.as_view(
            template_name="commons/password_change.html", success_url="/"
        ),
        name="change_password",
    ),
    # Forget Password
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="commons/password-reset/password_reset.html",
            subject_template_name="commons/password-reset/password_reset_subject.txt",
            success_url="/login/",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="commons/password-reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="commons/password-reset/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="commons/password-reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

credits/urls.py
from django.urls import path

from accounts.views import AccountLoginView
from credits.views import credit_list, apply_credit, approve_credit, active_credits

app_name = "credits"
urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("list/", credit_list, name="credit_list"),
    path("apply", apply_credit, name="apply_credit"),
    path("approve/<int:credit_app_id>/", approve_credit, name="approve_credit"),
    path("active_credits/", active_credits, name="active_credits"),
]

accounts/models.py
import random

from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

from django.contrib.auth.models import AbstractUser
from django.db import models, transaction

from .constants import CURRENCY, CARD_TYPE
from .managers import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=False, blank=False)
    objects = UserManager()

    USERNAME_FIELD = "email"
    is_active = models.BooleanField(
        default=True,
    )
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_cards(self):
        return self.user_cards.exists()


class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name="user_address",
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email


class Card(models.Model):
    card_name = models.CharField(max_length=100, default="New Card")
    using_system = models.BooleanField(default=False)
    account_no = models.CharField(max_length=16, unique=True)
    user = models.ForeignKey(
        User,
        related_name="user_cards",
        on_delete=models.CASCADE,
    )
    balance = models.DecimalField(default=0, max_digits=12, decimal_places=2)
    daily_balance = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(0.00)],
        default=0.00,
    )
    fixated_sum = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(0.00)],
        default=0.00,
    )
    pending_deposit_amount = models.DecimalField(
        default=0, max_digits=12, decimal_places=2
    )
    is_deposit_allowed = models.BooleanField(default=True)
    deposit_pending = models.BooleanField(default=False)
    cvv_code = models.CharField(max_length=3)
    card_type = models.CharField(max_length=1, choices=CARD_TYPE)
    currency = models.CharField(max_length=1, choices=CURRENCY)

    def save(self, *args, **kwargs):
        # Generate values for some fields
        if not self.account_no:
            self.account_no = "".join(str(random.randint(0, 9)) for _ in range(16))
        if not self.cvv_code:
            self.cvv_code = random.randint(100, 999)

        super().save(*args, **kwargs)

    def make_payment(self, amount, card_type):
        if card_type == "C":
            if not self.is_deposit_allowed:
                return False, "Deposit not allowed for credits card"
        elif card_type == "D":
            if self.using_system:
                if self.daily_balance < amount:
                    return (
                        False,
                        "Insufficient funds for debit card with daily budgeting system",
                    )
            else:
                if self.balance < amount:
                    return False, "Insufficient funds for debit card"
        else:
            return False, "Invalid card type"

        # Perform the payment transaction
        with transaction.atomic():
            # Create a Payment record
            Payment.objects.create(
                card=self,
                amount=amount,
                currency="B",
                card_type=card_type,
            )

            # Update the card balance
            self.balance -= amount
            if self.using_system:
                self.daily_balance -= amount
            self.save()

        return True, "Payment successful"

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}- {self.card_name} {self.balance} {self.currency}"


class BudgetSystem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=300)
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name="card")
    savings_card = models.ForeignKey(
        Card, on_delete=models.DO_NOTHING, related_name="savings_card"
    )
    daily_control = models.BooleanField(default=False)
    daily_percent = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10)], default=3, null=True
    )
    daily_redirect = models.BooleanField(default=False)
    savings_percent = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)], default=30
    )

    def save(self, *args, **kwargs):
        if not self.savings_card:
            self.daily_redirect = False
            self.redirect_savings = False
        if not self.daily_control:
            self.daily_percent = None
            self.daily_redirect = False

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}: {self.description}"


class Payment(models.Model):
    card = models.ForeignKey(
        Card,
        related_name="card_payments",
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=1, choices=CURRENCY)
    card_type = models.CharField(max_length=1, choices=CARD_TYPE)
    timestamp = models.DateTimeField(default=timezone.now)
    deposit_pending = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.card.id} - {self.amount} {self.currency} ({self.timestamp})"

accounts/forms.py
from datetime import datetime, timedelta

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms import SelectDateWidget
from .models import User, UserAddress, Card, BudgetSystem
from .constants import GENDER_CHOICE, CARD_TYPE, CURRENCY

# Sign Up Form


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional")
    email = forms.EmailField(max_length=254, help_text="Enter a valid email address")

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAddress
        fields = ["street_address", "city", "postal_code", "country"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    "class": (
                        "appearance-none block w-full bg-gray-200 "
                        "text-gray-700 border border-gray-200 rounded "
                        "py-3 px-4 leading-tight focus:outline-none "
                        "focus:bg-white focus:border-gray-500"
                    )
                }
            )


class UserRegistrationForm(UserCreationForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICE)
    birth_date = forms.DateField()

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    "class": (
                        "appearance-none block w-full bg-gray-200 "
                        "text-gray-700 border border-gray-200 "
                        "rounded py-3 px-4 leading-tight "
                        "focus:outline-none focus:bg-white "
                        "focus:border-gray-500"
                    )
                }
            )

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput)
    new_password1 = forms.CharField(widget=forms.PasswordInput)
    new_password2 = forms.CharField(widget=forms.PasswordInput)


class CardCreationForm(forms.ModelForm):
    card_name = forms.CharField()
    card_type = forms.ChoiceField(choices=CARD_TYPE)
    currency = forms.ChoiceField(choices=CURRENCY)

    class Meta:
        model = Card
        fields = [
            "card_name",
            "card_type",
            "currency",
        ]


class EmailVerificationForm(forms.Form):
    email = forms.EmailField(label="Email")
    verification_code = forms.CharField(label="Verification Code")


class DepositCardForm(forms.Form):
    deposit_amount = forms.DecimalField()


class PaymentForm(forms.Form):
    amount = forms.DecimalField(required=True)
    card = forms.ModelChoiceField(
        queryset=None, empty_label="Select Card", label="Select Card"
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        user_cards = Card.objects.filter(user=user)
        self.fields["card"].queryset = user_cards

    def clean_amount(self):
        amount = self.cleaned_data["amount"]
        if amount <= 0:
            raise forms.ValidationError("Amount must be greater than zero.")
        return amount


class CustomSelectDateWidget(SelectDateWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Allow selecting years that are more than 30 years in the past
        current_year = datetime.now().year
        self.years = range(current_year - 5, current_year + 1)


class StatementFilterForm(forms.Form):
    start_date = forms.DateField(
        widget=CustomSelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day")
        )
    )
    end_date = forms.DateField(
        widget=CustomSelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day")
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set the default end_date to today
        self.fields["end_date"].initial = datetime.now().date()

        # Set the default start_date to one month before the end_date
        default_start_date = self.fields["end_date"].initial - timedelta(days=30)
        self.fields["start_date"].initial = default_start_date

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        # Ensure start_date is not after end_date
        if start_date and end_date and start_date > end_date:
            raise forms.ValidationError("Start date cannot be after end date")

        return cleaned_data


class DepositApprovalForm(forms.Form):
    approved = forms.BooleanField(label="Approve deposit", required=False)


class BudgetSystemForm(forms.ModelForm):
    card = forms.ModelChoiceField(
        queryset=None, empty_label="Select Card", label="Select Card"
    )
    savings_card = forms.ModelChoiceField(
        queryset=None, empty_label="Select Savings Card", label="Select Savings Card"
    )
    daily_control = forms.BooleanField(label="Control daily", required=False)
    daily_redirect = forms.BooleanField(label="Redirect daily", required=False)

    class Meta:
        model = BudgetSystem
        fields = [
            "name",
            "description",
            "daily_percent",
            "savings_percent",
            "card",
            "savings_card",
            "daily_control",
            "daily_redirect",
        ]

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        user_cards = Card.objects.filter(user=user)
        self.fields["card"].queryset = user_cards
        self.fields["savings_card"].queryset = user_cards

templates/accounts/budgeting_systems_list.html
{% extends 'core/base.html' %}

{% block content %}
<h2 class="text-2xl font-semibold mb-4 mt-4">Active Budgeting Systems</h2>
{% if active_budgeting_systems %}
  <table class="min-w-full">
    <thead>
      <tr>
        <th class="py-2 ">Budgeting System Name</th>
        <th class="py-2 pl-0">Description</th>
        <th class="py-2 pl-0">Card</th>
        <th class="py-2 pl-0">Savings card</th>
        <th class="py-2 pl-0">Daily control</th>
        <th class="py-2 pl-0">Daily percent</th>
        <th class="py-2 pl-0">Daily budget</th>
        <th class="py-2 pl-0">Budget left for the day</th>
        <th class="py-2 pl-0">Savings percent</th>
      </tr>
    </thead>
    <tbody>
      {% for system in active_budgeting_systems %}
        <tr>
          <td class="py-2 pl-0 text-center">{{ system.name }}</td>
          <td class="py-2 pl-0 text-center">{{ system.description }}</td>
          <td class="py-2 pl-0 text-center">{{ system.card }}</td>
          <td class="py-2 pl-0 text-center">{{ system.savings_card }}</td>
          <td class="py-2 pl-0 text-center">{{ system.daily_control }}</td>
          <td class="py-2 pl-0 text-center">{{ system.daily_percent }}</td>
          <td class="py-2 pl-0 text-center">{{ system.card.fixated_sum }}</td>
          <td class="py-2 pl-0 text-center">{{ system.card.daily_balance }}</td>
          <td class="py-2 pl-0 text-center">{{ system.savings_percent }}</td>
            <td class="py-2 pl-0 text-center">
            <form method="post" action="{% url 'accounts:delete_budgeting_system' system.id %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="text-red-500 hover:underline ml-2">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No budget systems</p>
{% endif %}
{% endblock %}

templates/accounts/card_list.html
{% extends 'core/base.html' %}
{% block content %}
      <style>
      .card-container {
        transition: transform 0.3s;
      }

      .card-container:hover {
          transform: scale(1.03)  !important;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1)  !important;
      }
    </style>
  <div class="container mx-auto mt-8">
    <h2 class="text-3xl font-semibold mb-4 ">Your cards</h2>
    <div class="flex items-center justify-center mt-4 mb-8">
        <button class="bg-blue-500 text-center hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            <a href="{% url 'accounts:create_card' %}">Create a new card</a>
        </button>
      </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:w-1/2 md:w-full lg:w-full">
      {% for card in cards %}
       <div class="bg-white rounded-lg overflow-hidden shadow-md card-container">
          <div class="p-4">
            <h5 class="text-xl font-semibold mb-2">{{ card.card_name }}</h5>
              <p class="text-gray-600 mb-2">Card Type: {{ card.get_card_type_display }}</p>
            <p class="text-gray-600 mb-2">Balance: {{ card.balance }} {{ card.get_currency_display }}</p>
            <p class="text-gray-600 mb-2">Card Number: {{ card.account_no }}</p>
            <p class="text-gray-600 mb-2">CVV: <span id="cvv-{{ card.id }}" class="cvv-password">***</span>
              <button class="text-blue-500 hover:underline focus:outline-none focus:underline btn-sm show-cvv" data-card-id="{{ card.id }}" data-cvv-code="{{ card.cvv_code }}">Show CVV</button>
            </p>
                <div class="flex items-center justify-center mt-3">
                    <button class="bg-blue-700 text-center hover:bg-blue-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        <a href="{% url 'accounts:card_history' card.id %}">History</a>
                    </button>
                      <button class="bg-orange-700 ml-8 text-center hover:bg-orange-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        <a href="{% url 'accounts:deposit_form' card.id %}">Deposit</a>
                    </button>
                </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.show-cvv').forEach(function(btn) {
      btn.addEventListener('click', function() {
        let cardId = this.dataset.cardId;
        let cvvCode = this.dataset.cvvCode;
        let cvvElement = document.getElementById('cvv-' + cardId);

        if (cvvElement.textContent === cvvCode) {
          cvvElement.textContent = '***';
        } else {
          cvvElement.textContent = cvvCode;
        }
      });
    });
  });
</script>

{% endblock %}

templates/accounts/create_budgeting_system.html
{% extends 'core/base.html' %}

{% block content %}
      <h2 class="flex text-2xl font-semibold mt-4 justify-center">Create a Budgeting System</h2>
<div class="w-full mt-10">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 max-w-md mx-auto">
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {% if field.name == "savings_card"%}
                <div class="mb-4">
                  <label class="block text-gray-700 text-sm font-bold mb-2" for="id_savings_card">
                      {{ field.label }}
                  </label>
                {{ form.savings_card }}
                </div>
            {% endif %}
            {% if field.name == "card"%}
                <div class="mb-4">
                  <label class="block text-gray-700 text-sm font-bold mb-2" for="id_card">
                      {{ field.label }}
                  </label>
                {{ form.card }}
                </div>
            {% endif %}
            {% if field.name == "name" or field.name == "description" or field.name == "daily_percent" or field.name == "savings_percent" %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    <input
                        class="shadow appearance-none border border-gray-300 rounded-md w-full mt-1 p-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        name="{{ field.name }}"
                        id="{{ field.id_for_label }}"
                        type="{{ field.widget_type }}"
                        placeholder="{{ field.label }}"
                    >

                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="text-red-600 text-sm italic mt-1">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}
            {% if field.name == "daily_control"%}
                <div class="mb-4">
                  <label class="block text-gray-700 text-sm font-bold mb-2" for="id_savings_card">
                      {{ field.label }}
                  </label>
                {{ form.daily_control }}
                </div>
            {% endif %}

            {% if field.name == "daily_redirect"%}
                <div class="mb-4">
                  <label class="block text-gray-700 text-sm font-bold mb-2" for="id_savings_card">
                      {{ field.label }}
                  </label>
                {{ form.daily_redirect }}
                </div>
            {% endif %}
        {% endfor %}

        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Create
            </button>
        </div>
    </form>
</div>
{% endblock %}

templates/accounts/delete_budgeting_system.html
{% extends 'core/base.html' %}
{% block content %}
  <h2 class="text-2xl font-semibold mb-4">Delete Budgeting System</h2>

  <p>Are you sure you want to delete the budgeting system "{{ system.name }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
      Confirm Delete
    </button>
  </form>

  <a href="{% url 'accounts:budgeting_systems_list' %}" class="text-blue-500 hover:underline mt-2">Cancel</a>
{% endblock %}

templates/accounts/deposit_approval_form.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
  <h2 class="text-2xl font-semibold mb-4">Deposits Approval</h2>

  <form method="post">
    {% csrf_token %}

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="id_approved">
        Approve a deposit
      </label>
      <input type="checkbox" id="id_approved" name="approved" class="mr-2 leading-tight">
      <span class="text-sm text-gray-600">Check this box to approve the deposit.</span>
    </div>

    <div class="mb-4">
      <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Submit
      </button>
    </div>
  </form>
</div>
{% endblock %}

templates/accounts/deposit_approval_list.html
{% extends 'core/base.html' %}
{% block content %}
<div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
  <h2 class="text-2xl font-semibold mb-4">Pending Deposit Requests</h2>

  <ul>
    {% if pending_deposit_cards%}
    {% for card in pending_deposit_cards %}
      <li class="border-b border-gray-300 py-4">
        <div class="flex items-center justify-between">
          <div>
              <span class="text-gray-700 font-bold">Client:</span> {{ card.user.first_name }}{{ card.user.last_name }} <br>
            <span class="text-gray-700 font-bold">Card Number:</span> {{ card.account_no }} <br>
            <span class="text-gray-700 font-bold">Pending Amount:</span> {{ card.pending_deposit_amount }} {{ card.currency }}
          </div>
          <a href="{% url 'accounts:deposit_approval' card.id %}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Review
          </a>
        </div>
      </li>
    {% endfor %}
  {% else %}
         <h4 class="text-md mb-4">No active pending deposit requests</h4>
  {% endif %}
  </ul>
</div>
{% endblock %}

templates/accounts/deposit_form.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="max-w-md mx-auto mt-8 bg-white p-8 shadow-md">
        <h2 class="flex items-center justify-center text-2xl font-semibold mb-6">Make a Deposit</h2>
        <form method="post" action="{% url 'accounts:deposit_form' card.id %}" class="space-y-4">
            {% csrf_token %}
            <div class="items-center justify-center mb-8">
                <label for="deposit_amount" class="block text-sm font-medium text-gray-600">Deposit Amount</label>
                <input type="text" name="deposit_amount" id="deposit_amount" class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="Enter the deposit amount">
            </div>
             {% if form.deposit_amount.errors %}
                    {% for error in form.deposit_amount.errors %}
                        <p class="text-red-600 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}

            <div class="flex items-center justify-center">
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md">Deposit</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/accounts/edit_user_address.html
{% extends 'core/base.html' %}

{% block content %}
    <form id="userAddressForm" method="post" data-url="{% url 'accounts:edit_profile' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

templates/accounts/no_cards.html
{% extends 'core/base.html' %}

{% block content %}
  <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">No Cards Available</h1>
  <p class="text-center">You don't have any cards yet. Please create a card to continue.</p>
    <div class="flex items-center justify-center mt-8">
        <button class="bg-blue-500 text-center hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            <a href="{% url 'accounts:create_card' %}">Create a card</a>
        </button>
    </div>
{% endblock %}

templates/accounts/payment_form.html
{% extends 'core/base.html' %}
{% block content %}

    <div class="max-w-md mx-auto mt-8 bg-white p-8 shadow-md">
        <h2 class="flex items-center justify-center text-2xl font-semibold mb-6">Make a Payment</h2>

        <form method="post" action="{% url 'accounts:make_payment' %}" class="space-y-4">
            {% csrf_token %}

            <div class=" items-center justify-center mb-8">
                <label for="amount" class="block text-sm font-medium text-gray-600">Amount</label>
                <input type="text" name="amount" id="amount" class="mt-1 p-2 border border-gray-300 rounded-md w-full" placeholder="Enter the amount">
            </div>
            {% if form.amount.errors %}
                    {% for error in form.amount.errors %}
                        <p class="text-red-600 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}

            <div>
                {{ form.card }}
            </div>
            <div class="flex items-center justify-center mt-8">
                    <button type="submit" class="mx-auto bg-blue-500 text-white px-4 py-2 rounded-md mt-5">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/accounts/staff_profile.html
{% extends 'core/base.html' %}

{% block content %}
  <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Account Is Staff</h1>
  <p class="text-center">This account is a staff account, which doesn't hold any profile info. Please logout to view this section.</p>
{% endblock %}