accounts/urls.py
from django.urls import path
from .views import (
    LogoutView,
    UserProfileView,
    CardCreateView,
    CardListView,
    deposit_card,
    StaffProfileView,
    make_payment,
    statement,
    deposit_approval,
    deposit_approval_list,
    create_budgeting_system,
    budgeting_systems_list,
    delete_budgeting_system,
    EditUserAddressView,
    AccountLoginView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("profile-edit/", EditUserAddressView.as_view(), name="edit_profile"),
    path("staff_profile/", StaffProfileView.as_view(), name="staff_profile"),
    path("make_payment/", make_payment, name="make_payment"),
    path("create_card/", CardCreateView.as_view(), name="create_card"),
    path("card_list/", CardListView.as_view(), name="card_list"),
    path("card_history/<int:card_id>", statement, name="card_history"),
    path("deposit_card/<int:card_id>", deposit_card, name="deposit_form"),
    path("deposit-approval/", deposit_approval_list, name="deposit_approval_list"),
    path("deposit-approval/<int:card_id>/", deposit_approval, name="deposit_approval"),
    path(
        "budgeting-system/create/",
        create_budgeting_system,
        name="create_budgeting_system",
    ),
    path(
        "budgeting-systems-list/", budgeting_systems_list, name="budgeting_systems_list"
    ),
    path(
        "delete-budgeting-system/<int:budgeting_system_id>/",
        delete_budgeting_system,
        name="delete_budgeting_system",
    ),
]

banking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import include, path

from accounts.views import AccountLoginView, SignUpView
from core.views import HomeView


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("admin/", admin.site.urls),
    path("transactions/", include("transactions.urls", namespace="transactions")),
    path("credits/", include("credits.urls", namespace="credits")),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    # Change Password
    path(
        "change-password/",
        PasswordChangeView.as_view(
            template_name="commons/password_change.html", success_url="/"
        ),
        name="change_password",
    ),
    # Forget Password
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="commons/password-reset/password_reset.html",
            subject_template_name="commons/password-reset/password_reset_subject.txt",
            success_url="/login/",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="commons/password-reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="commons/password-reset/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="commons/password-reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

credits/urls.py
from django.urls import path

from accounts.views import AccountLoginView
from credits.views import credit_list, apply_credit, approve_credit, active_credits

app_name = "credits"
urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("list/", credit_list, name="credit_list"),
    path("apply", apply_credit, name="apply_credit"),
    path("approve/<int:credit_app_id>/", approve_credit, name="approve_credit"),
    path("active_credits/", active_credits, name="active_credits"),
]

transactions/urls.py
from django.urls import path

from accounts.views import AccountLoginView
from .views import fund_transfer, fund_transfer_card_by_card, TransactionMenu

app_name = "transactions"


urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("fund_transfer/", fund_transfer, name="fund_transfer"),
    path(
        "fund_transfer_card_by_card/",
        fund_transfer_card_by_card,
        name="fund_transfer_card_by_card",
    ),
    path("transaction_menu/", TransactionMenu.as_view(), name="transaction_menu"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "core/index.html"

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Banking System" />
        <meta name="author" content="Maksudul Haque" />
        <title>
            {% block head_title %}Banking System{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

        {% block head_extra %}{% endblock %}
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>
</html>

templates/core/footer.html
<footer class="footer bg-gray-200 relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-6">
                <p class="text-md text-gray-900 font-bold mb-2">
                    © 2023 by Sorokina Catherine, group 053504</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/core/index.html
{% extends 'core/base.html' %}

{% block head_title %}Banking System{% endblock %}

{% block content %}
    <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
        <!--Left Col-->
        <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-12 pb-24 px-6">
            <h1 class="font-bold text-4xl my-4">Banking System</h1>
            <p class="leading-normal mb-4">
                WELCOME to the Banking System
            </p>
            <div>
              
            </div>
        </div>
        <!--Right Col-->
        <div class="w-full lg:w-1/2 lg:py-6 text-center">
            <h1 style="font-size: 12rem" class="font-black text-gray-800"></h1>
        </div>
    </div>
{% endblock %}

templates/core/messages.html
{% for message in messages %}
  <div class="{% if message.tags == 'success' %}bg-teal-100 border-t-4 border-teal-500{% else %}bg-red-100 border-t-4 border-red-500{% endif %} rounded-b text-{{ message.tags }}-900 px-4 py-3 shadow-md mt-2" role="alert">
      <div class="flex">
          <div class="py-1">
              {% if message.tags == 'success' %}
                  <svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                      <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/>
                  </svg>
              {% else %}
                  <svg class="fill-current h-6 w-6 text-red-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                      <path d="M10 12a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM11 15H9a1 1 0 0 0 0 2h2a1 1 0 0 0 0-2zm0-9H9a1 1 0 0 0 0 2h2a1 1 0 0 0 0-2z"/>
                  </svg>
              {% endif %}
          </div>
          <div>
              <p class="font-bold">{{ message.tags|title }}</p>
              <p class="text-sm">{{ message }}</p>
          </div>
      </div>
  </div>
{% endfor %}

templates/core/navbar.html
<style>
    .group:hover .absolute {
    display: block;
}
</style>
<nav id="mainNav" class="flex items-center justify-between flex-wrap bg-gray-800 p-6">

    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight"><a href="{% url 'home' %}">SorokaBank</a></span>
    </div>
    <div class="block lg:hidden">
        <button id="mobileMenuButton" class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>

    <div id="menuItems" class="w-full block flex-grow lg:flex lg:items-center lg:w-auto hidden">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                {% if request.user.is_staff %}
                    <a href="{% url 'accounts:staff_profile' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                        Staff account
                    </a>
                {% else %}
                    <a href="{% url 'accounts:user_profile' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                        My account
                    </a>
                {% endif %}
             {% if request.user.is_staff %}
                    <a href="{% url 'accounts:deposit_approval_list' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                         Client Deposits
                    </a>
                {% else %}
                    <a href="{% url 'accounts:make_payment' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                         Payment
                    </a>
                {% endif %}
            {% if request.user.is_staff %}
                {% else %}
                    <a href="{% url 'transactions:transaction_menu' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                         Transfers
                    </a>
                {% endif %}
            {% if request.user.is_staff %}
                    <a href="{% url 'credits:credit_list' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                         Client Credits
                    </a>
                {% else %}
                    <a href="{% url 'credits:apply_credit' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                         New Credit
                    </a>
                    <a href="{% url 'credits:active_credits' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                         Active Credits
                    </a>
                    <a href="{% url 'accounts:create_budgeting_system' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                        Create Budgeting System
                    </a>
                  <a href="{% url 'accounts:budgeting_systems_list' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                        Active Budgeting Systems
                    </a>
                {% endif %}


            </div>
             {% if not request.user.is_staff %}
              <div>
                <a href="{% url 'accounts:card_list' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 mr-3 lg:mt-0">Cards</a>
            </div>
             {% endif %}
            <div>
                <a href="{% url 'accounts:user_logout' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">LogOut</a>
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'login' %}" class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">LogIn</a>
            </div>
            <div>
                <a href="{% url 'signup' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a>
            </div>
        {% endif %}
    </div>
</nav>

<script>
    const mobileMenuButton = document.getElementById("mobileMenuButton");
    const menuItems = document.getElementById("menuItems");

    mobileMenuButton.addEventListener("click", () => {
        menuItems.classList.toggle("hidden");
    });
</script>